! Node b3: bootstrap. Transport(lo) 10.99.5.3 | Router-ID 10.0.5.3 | ASN 65303
!
! eth1 -> b2 (real underlay eBGP session, see bgpd-b1.conf's header comment).
frr version 10.0
hostname node-ga-b3
log file logs/bgpd-b3.log debugging
log timestamp precision 3

debug bgp midr

interface eth1
 ip address 10.10.55.6/30
!
interface lo
 ip address 10.99.5.3/32
!
route-map UNDERLAY-PERMIT permit 10
!
router bgp 65303
  bgp router-id 10.0.5.3
  no bgp network import-check

  midr transport-address 10.99.5.3
  midr role bootstrap
  midr session 10.99.5.1 remote-as 65301
  midr session 10.99.5.2 remote-as 65302
  midr bootstrap 10.99.5.1 remote-as 65301 router-id 10.0.5.1
  midr bootstrap 10.99.5.2 remote-as 65302 router-id 10.0.5.2

  neighbor 10.10.55.5 remote-as 65302
  !
  address-family ipv4 unicast
    redistribute connected
    neighbor 10.10.55.5 route-map UNDERLAY-PERMIT in
    neighbor 10.10.55.5 route-map UNDERLAY-PERMIT out
  exit-address-family
!
