! Node b3: bootstrap. Transport(lo) 10.99.5.3 | Router-ID 10.0.5.3 | ASN 65303
frr version 10.0
hostname node-ga-b3
log file logs/bgpd-b3.log debugging
log timestamp precision 3

debug bgp midr

router bgp 65303
  bgp router-id 10.0.5.3
  no bgp ebgp-requires-policy
  no bgp network import-check

  address-family link-state link-state
    distribute bgp-fabric-link-state
  exit-address-family

  midr transport-address 10.99.5.3
  midr role bootstrap
  midr session 10.99.5.1 remote-as 65301
  midr session 10.99.5.2 remote-as 65302
  midr bootstrap 10.99.5.1 remote-as 65301 router-id 10.0.5.1
  midr bootstrap 10.99.5.2 remote-as 65302 router-id 10.0.5.2
!
