frr version 10.7.0-dev
frr defaults traditional
hostname t3
log file /etc/frr/logs/frr.log
!
! eth1 -> t2
interface eth1
 ip address 10.10.2.2/30
!
! eth2 -> t1
interface eth2
 ip address 10.10.3.2/30
!
! eth3 -> b4
interface eth3
 ip address 10.10.14.2/30
!
! eth4 -> b5
interface eth4
 ip address 10.10.15.2/30
!
! eth5 -> m2a
interface eth5
 ip address 10.10.25.2/30
!
! eth6 -> z1
interface eth6
 ip address 10.10.31.2/30
!
interface lo
 ip address 10.99.0.203/32
!
router bgp 65203
 bgp router-id 10.0.0.203
 no bgp ebgp-requires-policy
 neighbor 10.10.2.1 remote-as 65202
 neighbor 10.10.3.1 remote-as 65201
 neighbor 10.10.14.1 remote-as 65104
 neighbor 10.10.15.1 remote-as 65105
 neighbor 10.10.25.1 remote-as 65122
 neighbor 10.10.31.1 remote-as 65191
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
!
