! Node b2: bootstrap. Transport(lo) 10.99.0.102 | Router-ID 10.0.0.102 | ASN 65102
frr version 10.0
hostname node-bb-b2
log file logs/bgpd-b2.log debugging
log timestamp precision 3

debug bgp midr

! eth1 -> t1
interface eth1
 ip address 10.10.12.1/30
!
interface lo
 ip address 10.99.0.102/32
!
route-map UNDERLAY-PERMIT permit 10
!
router bgp 65102
  bgp router-id 10.0.0.102
  no bgp network import-check

  midr transport-address 10.99.0.102
  midr role bootstrap
  midr session 10.99.0.101 remote-as 65101
  midr session 10.99.0.103 remote-as 65103
  midr session 10.99.0.104 remote-as 65104
  midr session 10.99.0.105 remote-as 65105
  midr bootstrap 10.99.0.101 remote-as 65101 router-id 10.0.0.101
  midr bootstrap 10.99.0.103 remote-as 65103 router-id 10.0.0.103
  midr bootstrap 10.99.0.104 remote-as 65104 router-id 10.0.0.104
  midr bootstrap 10.99.0.105 remote-as 65105 router-id 10.0.0.105

  neighbor 10.10.12.2 remote-as 65201
  !
  address-family ipv4 unicast
    redistribute connected
    neighbor 10.10.12.2 route-map UNDERLAY-PERMIT in
    neighbor 10.10.12.2 route-map UNDERLAY-PERMIT out
  exit-address-family
!
