! Node b1: bootstrap. Transport(lo) 10.99.0.101 | Router-ID 10.0.0.101 | ASN 65101
frr version 10.0
hostname node-bb-b1
log file logs/bgpd-b1.log debugging
log timestamp precision 3

debug bgp midr

! eth1 -> t1
interface eth1
 ip address 10.10.11.1/30
!
interface lo
 ip address 10.99.0.101/32
!
route-map UNDERLAY-PERMIT permit 10
!
router bgp 65101
  bgp router-id 10.0.0.101
  no bgp network import-check

  midr transport-address 10.99.0.101
  midr role bootstrap
  midr session 10.99.0.102 remote-as 65102
  midr session 10.99.0.103 remote-as 65103
  midr session 10.99.0.104 remote-as 65104
  midr session 10.99.0.105 remote-as 65105
  midr bootstrap 10.99.0.102 remote-as 65102 router-id 10.0.0.102
  midr bootstrap 10.99.0.103 remote-as 65103 router-id 10.0.0.103
  midr bootstrap 10.99.0.104 remote-as 65104 router-id 10.0.0.104
  midr bootstrap 10.99.0.105 remote-as 65105 router-id 10.0.0.105

  neighbor 10.10.11.2 remote-as 65201
  !
  address-family ipv4 unicast
    redistribute connected
    neighbor 10.10.11.2 route-map UNDERLAY-PERMIT in
    neighbor 10.10.11.2 route-map UNDERLAY-PERMIT out
  exit-address-family
!
