! Node b4: bootstrap. Transport(lo) 10.99.0.104 | Router-ID 10.0.0.104 | ASN 65104
frr version 10.0
hostname node-bb-b4
log file logs/bgpd-b4.log debugging
log timestamp precision 3

debug bgp midr

! eth1 -> t3
interface eth1
 ip address 10.10.14.1/30
!
interface lo
 ip address 10.99.0.104/32
!
route-map UNDERLAY-PERMIT permit 10
!
router bgp 65104
  bgp router-id 10.0.0.104
  no bgp network import-check

  midr transport-address 10.99.0.104
  midr role bootstrap
  midr session 10.99.0.101 remote-as 65101
  midr session 10.99.0.102 remote-as 65102
  midr session 10.99.0.103 remote-as 65103
  midr session 10.99.0.105 remote-as 65105
  midr bootstrap 10.99.0.101 remote-as 65101 router-id 10.0.0.101
  midr bootstrap 10.99.0.102 remote-as 65102 router-id 10.0.0.102
  midr bootstrap 10.99.0.103 remote-as 65103 router-id 10.0.0.103
  midr bootstrap 10.99.0.105 remote-as 65105 router-id 10.0.0.105

  neighbor 10.10.14.2 remote-as 65203
  !
  address-family ipv4 unicast
    redistribute connected
    neighbor 10.10.14.2 route-map UNDERLAY-PERMIT in
    neighbor 10.10.14.2 route-map UNDERLAY-PERMIT out
  exit-address-family
!
