! Node m1a: member. Transport(lo) 10.99.0.112 | Router-ID 10.0.0.112 | ASN 65112
frr version 10.0
hostname node-bb-m1a
log file logs/bgpd-m1a.log debugging
log timestamp precision 3

debug bgp midr

! eth1 -> t1
interface eth1
 ip address 10.10.22.1/30
!
interface lo
 ip address 10.99.0.112/32
!
route-map UNDERLAY-PERMIT permit 10
!
router bgp 65112
  bgp router-id 10.0.0.112
  no bgp network import-check

  midr transport-address 10.99.0.112
  midr group-id 1
  midr bootstrap 10.99.0.101 remote-as 65101 router-id 10.0.0.101
  midr bootstrap 10.99.0.102 remote-as 65102 router-id 10.0.0.102
  midr bootstrap 10.99.0.103 remote-as 65103 router-id 10.0.0.103
  midr bootstrap 10.99.0.104 remote-as 65104 router-id 10.0.0.104
  midr bootstrap 10.99.0.105 remote-as 65105 router-id 10.0.0.105

  neighbor 10.10.22.2 remote-as 65201
  !
  address-family ipv4 unicast
    redistribute connected
    neighbor 10.10.22.2 route-map UNDERLAY-PERMIT in
    neighbor 10.10.22.2 route-map UNDERLAY-PERMIT out
  exit-address-family
!
