frr version 10.7.0-dev
frr defaults traditional
hostname t2
log file /etc/frr/logs/frr.log
!
! eth1 -> t1
interface eth1
 ip address 10.10.1.2/30
!
! eth2 -> t3
interface eth2
 ip address 10.10.2.1/30
!
! eth3 -> b3
interface eth3
 ip address 10.10.13.2/30
!
! eth4 -> m1b
interface eth4
 ip address 10.10.23.2/30
!
! eth5 -> r2
interface eth5
 ip address 10.10.24.2/30
!
interface lo
 ip address 10.99.0.202/32
!
router bgp 65202
 bgp router-id 10.0.0.202
 no bgp ebgp-requires-policy
 neighbor 10.10.1.1 remote-as 65201
 neighbor 10.10.2.2 remote-as 65203
 neighbor 10.10.13.1 remote-as 65103
 neighbor 10.10.23.1 remote-as 65113
 neighbor 10.10.24.1 remote-as 65121
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
!
