#!/usr/bin/env python3
"""Derive the midrd variants of the backbone lab from the bgpd ones.

The topology, roles, addresses, underlay and the Tier1 scenario stay the
same.  Only where MIDR runs changes:

  - bgpd keeps the eBGP underlay and loses every `midr ...` line that sat
    under `router bgp` (group 1 and group 2 now run in midrd);
  - those lines move, in order, to the top level of frr.conf, where midrd
    installs them; `debug bgp midr` becomes `debug midr`, and every MIDR
    node logs the discovery flow (the checks read the CL decisions);
  - the daemons file starts midrd on the 12 MIDR nodes with the node id
    (the BGP Identifier's raw value), the transport as listen address and,
    on members, a service prefix for group 2 and SPF;
  - the topologies are unchanged (both already add the transport loopback
    before FRR starts, which midrd needs because it binds it at startup).

Usage: gen-midrd-lab.py   (rewrites configs-midrd/, configs-midrd-v6/,
                           midr-backbone-midrd.clab.yaml and
                           midr-backbone-midrd-v6.clab.yaml)
"""
import pathlib
import re
import shutil
import socket
import struct

HERE = pathlib.Path(__file__).resolve().parent
MIDR_PORT = 5871
HEADER = "! Generated by gen-midrd-lab.py; do not edit by hand.\n"

VARIANTS = [
    # source configs, source topology, target configs, target topology
    ("configs-backbone", "midr-backbone.clab.yaml",
     "configs-midrd", "midr-backbone-midrd.clab.yaml", 4),
    ("configs-backbone-v6", "midr-backbone-v6.clab.yaml",
     "configs-midrd-v6", "midr-backbone-midrd-v6.clab.yaml", 6),
]


def node_id(router_id):
    """midrd's node id is the BGP Identifier's s_addr as stored on the host."""
    return struct.unpack("=I", socket.inet_aton(router_id))[0]


def split_config(text):
    """Move `midr` lines out of `router bgp`.

    Returns (conf, router_id, transport)."""
    out = []
    midr = []
    router_id = transport = None
    in_bgp = False
    debug_seen = False
    for line in text.splitlines():
        if line.startswith("! Generated by "):
            continue
        if line.startswith("router bgp "):
            in_bgp = True
        elif in_bgp and line == "!":
            # vtysh stays in the router node across "!": without an explicit
            # exit, top-level `midr` lines that also exist under `router bgp`
            # would be sent to bgpd.
            out.append("exit")
            out.append(line)
            if midr:
                out.append("! MIDR（midrd 第一组）：原先写在 router bgp 下的配置")
                if not debug_seen:
                    # CL decisions are debug logs; the checks read them.
                    out.append("debug midr discovery")
                out.extend(midr)
                out.append("!")
            in_bgp = False
            continue
        m = re.match(r"^ bgp router-id (\S+)$", line)
        if m:
            router_id = m.group(1)
        if line == "debug bgp midr discovery":
            out.append("debug midr discovery")
            debug_seen = True
            continue
        if line == "debug bgp midr":
            out.append("debug midr")
            continue
        if in_bgp and re.match(r"^ +midr prefix-export ", line):
            # bgpd's Prefix feed to its own group 2; midrd takes --prefix.
            continue
        m = re.match(r"^ midr (.*)$", line)
        if in_bgp and m:
            midr.append("midr " + m.group(1))
            t = re.match(r"^transport-address (\S+)$", m.group(1))
            if t:
                transport = t.group(1)
            continue
        out.append(line)
    return "\n".join(out) + "\n", router_id, transport


def daemons_file(text, options):
    lines = [l for l in text.splitlines() if not l.startswith("midrd")]
    if options is None:
        lines.append("midrd=no")
    else:
        lines.append("midrd=yes")
        lines.append('midrd_options="%s"' % options)
    return "\n".join(lines) + "\n"


def convert_topology(text, name):
    text = re.sub(r"^name: .*$", "name: %s" % name, text, count=1,
                  flags=re.MULTILINE)
    text = re.sub(r"^# Generated by .*\n", "", text, flags=re.MULTILINE)
    return ("# Generated by gen-midrd-lab.py; do not edit by hand.\n" + text)


def main():
    for src_cfg, src_topo, dst_cfg, dst_topo, family in VARIANTS:
        src_cfg = HERE / src_cfg
        dst_cfg = HERE / dst_cfg
        if dst_cfg.exists():
            shutil.rmtree(dst_cfg)
        for node_dir in sorted(p for p in src_cfg.iterdir() if p.is_dir()):
            node = node_dir.name
            dst = dst_cfg / node
            dst.mkdir(parents=True)
            conf, router_id, transport = split_config(
                (node_dir / "frr.conf").read_text())
            (dst / "frr.conf").write_text(HEADER + conf)
            options = None
            if transport:
                num = (transport.rsplit(".", 1)[-1] if family == 4
                       else transport.rsplit(":", 1)[-1])
                listen = ("%s:%d" % (transport, MIDR_PORT) if family == 4
                          else "[%s]:%d" % (transport, MIDR_PORT))
                options = ("--node-id %d --listen %s"
                           % (node_id(router_id), listen))
                if not node.startswith("b"):
                    prefix = ("198.18.0.%s/32" % num if family == 4
                              else "fd00:18::%s/128" % num)
                    options += " --prefix %s" % prefix
                options += (" --log file:/etc/frr/logs/midrd.log"
                            " --log-level debug")
            (dst / "daemons").write_text(
                daemons_file((node_dir / "daemons").read_text(), options))
            policy = node_dir / "midr-policy"
            if policy.is_dir():
                shutil.copytree(policy, dst / "midr-policy")
        name = pathlib.Path(dst_topo).stem.replace(".clab", "")
        (HERE / dst_topo).write_text(convert_topology(
            (HERE / src_topo).read_text(), name))
        print("wrote %s and %s" % (dst_cfg.name, dst_topo))


if __name__ == "__main__":
    main()
