#!/usr/bin/env python3
"""Derive the IPv6-only backbone lab from the IPv4 one.

The topology, roles, ASNs and BGP identifiers stay the same.  Every link,
transport and underlay address becomes IPv6:

  10.10.S.H/30  ->  fd00:10:S::H/64     (point-to-point link)
  10.99.0.N/32  ->  fd00:99::N/128      (transport loopback)
  10.0.0.N      ->  unchanged           (BGP Identifier only)

Each node enables IPv6 forwarding, disables IPv4 forwarding, runs the
underlay in the IPv6 unicast family only, and removes the containerlab
management addresses from eth0 before FRR starts, so no global IPv4 address
remains and MIDR cannot fall back to the management network.

Usage: gen-ipv6-lab.py   (rewrites configs-backbone-v6/ and
                          midr-backbone-v6.clab.yaml next to this script)
"""
import pathlib
import re
import shutil
import sys

HERE = pathlib.Path(__file__).resolve().parent
SRC_CFG = HERE / "configs-backbone"
DST_CFG = HERE / "configs-backbone-v6"
SRC_TOPO = HERE / "midr-backbone.clab.yaml"
DST_TOPO = HERE / "midr-backbone-v6.clab.yaml"

LINK_RE = re.compile(r"\b10\.10\.(\d+)\.(\d+)\b")
LOOP_RE = re.compile(r"\b10\.99\.0\.(\d+)\b")

# Runs as the image user; sudo is passwordless there.
STRIP_MGMT = [
    "sudo -n ip -4 route flush table main",
    "sudo -n ip -4 addr flush dev eth0",
    "sudo -n ip -6 route flush default",
    "sudo -n ip -6 addr flush dev eth0 scope global",
]


def v6_addresses(text):
    text = LINK_RE.sub(r"fd00:10:\1::\2", text)
    return LOOP_RE.sub(r"fd00:99::\1", text)


def convert_frr_conf(text):
    out = []
    underlay = []
    in_af = False
    for line in v6_addresses(text).splitlines():
        m = re.match(r"^ ip address (\S+)/30$", line)
        if m:
            out.append(" ipv6 address %s/64" % m.group(1))
            continue
        m = re.match(r"^ ip address (\S+)/32$", line)
        if m:
            out.append(" ipv6 address %s/128" % m.group(1))
            continue
        if line.startswith("log file "):
            out.append(line)
            out.append("!")
            out.append("ipv6 forwarding")
            out.append("no ip forwarding")
            continue
        m = re.match(r"^ bgp router-id ", line)
        if m:
            out.append(line)
            out.append(" no bgp default ipv4-unicast")
            continue
        m = re.match(r"^ neighbor (fd00:10:\S+) remote-as ", line)
        if m:
            underlay.append(m.group(1))
        if line == " address-family ipv4 unicast":
            out.append(" address-family ipv6 unicast")
            out.extend("  neighbor %s activate" % peer for peer in underlay)
            in_af = True
            continue
        if in_af and line == " exit-address-family":
            in_af = False
        out.append(line)
    return "\n".join(out) + "\n"


def convert_prefix2as(text):
    text = v6_addresses(text)
    text = re.sub(r"^(fd00:\S+)/32 ", r"\1/128 ", text, flags=re.MULTILINE)
    return text.replace("Lab-only IP-to-ASN snapshot for z1",
                        "Lab-only IPv6 IP-to-ASN snapshot for z1")


def convert_topology(text):
    text = text.replace("name: midr-backbone\n", "name: midr-backbone-v6\n", 1)
    strip = "".join("        - %s\n" % cmd for cmd in STRIP_MGMT)
    text = text.replace("      exec:\n", "      exec:\n" + strip)
    return ("# Generated by gen-ipv6-lab.py from midr-backbone.clab.yaml; "
            "do not edit by hand.\n" + text)


def main():
    if DST_CFG.exists():
        shutil.rmtree(DST_CFG)
    for node_dir in sorted(p for p in SRC_CFG.iterdir() if p.is_dir()):
        dst = DST_CFG / node_dir.name
        dst.mkdir(parents=True)
        shutil.copy2(node_dir / "daemons", dst / "daemons")
        conf = convert_frr_conf((node_dir / "frr.conf").read_text())
        (dst / "frr.conf").write_text(
            "! Generated by gen-ipv6-lab.py; do not edit by hand.\n" + conf)
        policy = node_dir / "midr-policy"
        if policy.is_dir():
            (dst / "midr-policy").mkdir()
            shutil.copy2(policy / "tier1_asns.txt",
                         dst / "midr-policy" / "tier1_asns.txt")
            (dst / "midr-policy" / "prefix2as.txt").write_text(
                convert_prefix2as((policy / "prefix2as.txt").read_text()))
    DST_TOPO.write_text(convert_topology(SRC_TOPO.read_text()))

    leftover = [str(p) for p in DST_CFG.rglob("*")
                if p.is_file() and re.search(r"\b10\.(10|99)\.", p.read_text())]
    if leftover:
        sys.exit("IPv4 addresses left in: " + ", ".join(leftover))
    print("wrote %s and %s" % (DST_CFG.relative_to(HERE), DST_TOPO.name))


if __name__ == "__main__":
    main()
