#!/usr/bin/env bash
# Build and deploy an isolated 15-node group1+group2 integration lab.
#
# MIDR_LAB_STACK=midrd (default): groups 1 and 2 run in midrd, bgpd carries
#   only the underlay; configs are generated by gen-midrd-lab.py.
# MIDR_LAB_STACK=bgpd: the original bgpd implementation, kept for reference.

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/../.." && pwd)
GIT=(git -c "safe.directory=$REPO_ROOT" -C "$REPO_ROOT")
REV=$("${GIT[@]}" rev-parse --short=12 HEAD)
# ipv4 (default) or ipv6; the IPv6-only variant is generated by gen-ipv6-lab.py.
FAMILY=${MIDR_LAB_FAMILY:-ipv4}
STACK=${MIDR_LAB_STACK:-midrd}
case "$STACK:$FAMILY" in
	bgpd:ipv4)
		CONFIG_SRC="$SCRIPT_DIR/configs-backbone"
		TOPOLOGY_SRC="$SCRIPT_DIR/midr-backbone.clab.yaml"
		DEFAULT_LAB_NAME=midr-backbone-yhy
		;;
	bgpd:ipv6)
		CONFIG_SRC="$SCRIPT_DIR/configs-backbone-v6"
		TOPOLOGY_SRC="$SCRIPT_DIR/midr-backbone-v6.clab.yaml"
		DEFAULT_LAB_NAME=midr-backbone-yhy-v6
		;;
	midrd:ipv4)
		CONFIG_SRC="$SCRIPT_DIR/configs-midrd"
		TOPOLOGY_SRC="$SCRIPT_DIR/midr-backbone-midrd.clab.yaml"
		DEFAULT_LAB_NAME=midr-backbone-midrd
		;;
	midrd:ipv6)
		CONFIG_SRC="$SCRIPT_DIR/configs-midrd-v6"
		TOPOLOGY_SRC="$SCRIPT_DIR/midr-backbone-midrd-v6.clab.yaml"
		DEFAULT_LAB_NAME=midr-backbone-midrd-v6
		;;
	*)
		printf 'ERROR: MIDR_LAB_STACK must be midrd or bgpd, MIDR_LAB_FAMILY ipv4 or ipv6\n' >&2
		exit 1
		;;
esac
LAB_NAME=${MIDR_LAB_NAME:-$DEFAULT_LAB_NAME}
LAB_PREFIX="clab-$LAB_NAME"
IMAGE=${MIDR_LAB_IMAGE:-frr-midr-g12:$REV}
UBUNTU_VERSION=${MIDR_UBUNTU_VERSION:-22.04}
RUN_ROOT=${MIDR_LAB_RUN_ROOT:-"$(dirname "$REPO_ROOT")/midr-lab-runs/$LAB_NAME"}
TOPOLOGY="$RUN_ROOT/midr-backbone.clab.yaml"
ACCEPTANCE="$REPO_ROOT/midr-test/backbone-group2/run_group1_group2_demo_check.sh"
CAPTURE="$REPO_ROOT/midr-test/backbone-group2/capture_group1_group2_state.sh"
VERIFY="$REPO_ROOT/midr-test/backbone-group2/verify_group1_group2_evidence.py"
TIER1_CHECK="$SCRIPT_DIR/check_tier1_admission.sh"
IPV6_CHECK="$SCRIPT_DIR/check_ipv6_only.sh"
if [ "$STACK" = midrd ]; then
	ACCEPTANCE="$SCRIPT_DIR/check_midrd_lab.sh"
fi
MODE=${1:-all}

die()
{
	printf 'ERROR: %s\n' "$*" >&2
	exit 1
}

require_command()
{
	command -v "$1" >/dev/null 2>&1 || die "required command is unavailable: $1"
}

ensure_root()
{
	# containerlab also runs without sudo for members of clab_admins.
	[ "$(id -u)" -eq 0 ] || id -nG | tr ' ' '\n' | grep -qx clab_admins ||
		die "this mode needs root or clab_admins; run: sudo -E $0 $MODE"
}

check_lab_name()
{
	case "$LAB_NAME" in
		*[!a-zA-Z0-9_-]*|'')
			die "MIDR_LAB_NAME may contain only letters, digits, '_' and '-'"
			;;
	esac
}

check_existing_lab()
{
	local existing

	existing=$(docker ps -a --format '{{.Names}}' |
		grep -E "^${LAB_PREFIX}-" || true)
	[ -z "$existing" ] || {
		printf 'An existing lab uses prefix %s:\n%s\n' "$LAB_PREFIX" "$existing" >&2
		die "refusing to replace or destroy an existing lab"
	}
}

preflight()
{
	require_command git
	require_command docker
	require_command containerlab
	require_command python3
	require_command sed
	require_command timeout
	check_lab_name

	docker info >/dev/null 2>&1 || die "Docker daemon is unavailable to the current user"
	containerlab version
	"${GIT[@]}" diff --check
	bash -n "$ACCEPTANCE"
	bash -n "$CAPTURE"
	bash -n "$TIER1_CHECK"
	bash -n "$IPV6_CHECK"
	[ -f "$CONFIG_SRC/z1/midr-policy/prefix2as.txt" ] &&
		[ -f "$CONFIG_SRC/z1/midr-policy/tier1_asns.txt" ] ||
		die "z1 Tier1 admission policy files are missing"
	if [ "$FAMILY" = ipv6 ] || [ "$STACK" = midrd ]; then
		python3 "$SCRIPT_DIR/gen-ipv6-lab.py" >/dev/null
		python3 "$SCRIPT_DIR/gen-midrd-lab.py" >/dev/null
		generated=("$SCRIPT_DIR/configs-backbone-v6" "$SCRIPT_DIR/midr-backbone-v6.clab.yaml"
			   "$SCRIPT_DIR/configs-midrd" "$SCRIPT_DIR/midr-backbone-midrd.clab.yaml"
			   "$SCRIPT_DIR/configs-midrd-v6" "$SCRIPT_DIR/midr-backbone-midrd-v6.clab.yaml")
		"${GIT[@]}" diff --quiet -- "${generated[@]}" &&
			[ -z "$("${GIT[@]}" ls-files --others --exclude-standard -- "${generated[@]}")" ] ||
			die "generated lab files are stale; commit the output of gen-ipv6-lab.py and gen-midrd-lab.py"
	fi
	python3 -c 'import ast, pathlib, sys; ast.parse(pathlib.Path(sys.argv[1]).read_text())' "$VERIFY"
	[ -f "$TOPOLOGY_SRC" ] || die "15-node topology is missing"
	[ "$(grep -c 'image: frr-ubuntu20:latest' "$TOPOLOGY_SRC")" -eq 15 ] ||
		die "the checked-in topology does not contain exactly 15 FRR nodes"
	[ "$(grep -c 'endpoints:' "$TOPOLOGY_SRC")" -eq 15 ] ||
		die "the checked-in topology does not contain exactly 15 links"

	printf 'Repository : %s\n' "$REPO_ROOT"
	printf 'Revision   : %s%s\n' "$REV" "$("${GIT[@]}" diff --quiet && "${GIT[@]}" diff --cached --quiet || printf ' + local changes')"
	printf 'Image      : %s\n' "$IMAGE"
	printf 'Ubuntu     : %s\n' "$UBUNTU_VERSION"
	printf 'Stack      : %s\n' "$STACK"
	printf 'Family     : %s\n' "$FAMILY"
	printf 'Lab name   : %s\n' "$LAB_NAME"
	printf 'Run root   : %s\n' "$RUN_ROOT"
	df -h "$REPO_ROOT" | tail -n 1
}

prepare_run_root()
{
	if [ -e "$RUN_ROOT" ]; then
		[ -f "$RUN_ROOT/build-metadata.txt" ] ||
			die "run directory already exists and was not prepared by this script: $RUN_ROOT"
		grep -qx "revision=$REV" "$RUN_ROOT/build-metadata.txt" &&
			grep -qx "family=$FAMILY" "$RUN_ROOT/build-metadata.txt" &&
			{ [ "$STACK" = bgpd ] || grep -qx "stack=$STACK" "$RUN_ROOT/build-metadata.txt"; } &&
			grep -qx "image=$IMAGE" "$RUN_ROOT/build-metadata.txt" &&
			grep -qx "lab_name=$LAB_NAME" "$RUN_ROOT/build-metadata.txt" ||
			die "existing run directory belongs to a different build: $RUN_ROOT"
		if grep -q '^ubuntu_version=' "$RUN_ROOT/build-metadata.txt"; then
			grep -qx "ubuntu_version=$UBUNTU_VERSION" "$RUN_ROOT/build-metadata.txt" ||
				die "existing run directory uses a different Ubuntu version: $RUN_ROOT"
		else
			printf 'ubuntu_version=%s\n' "$UBUNTU_VERSION" >>"$RUN_ROOT/build-metadata.txt"
		fi
		printf 'Reusing prepared run directory: %s\n' "$RUN_ROOT"
		return
	fi
	mkdir -p "$RUN_ROOT"
	cp -a "$CONFIG_SRC" "$RUN_ROOT/configs-backbone"
	mkdir -p "$RUN_ROOT/logs-backbone"
	for node in b1 b2 b3 b4 b5 t1 t2 t3 r1 r2 m1a m1b m2a z1 z2; do
		mkdir -p "$RUN_ROOT/logs-backbone/$node"
	done
	sed -e "s/^name: .*/name: $LAB_NAME/" \
		-e "s|image: frr-ubuntu20:latest|image: $IMAGE|g" \
		"$TOPOLOGY_SRC" >"$TOPOLOGY"
	{
		printf 'repository=%s\n' "$REPO_ROOT"
		printf 'revision=%s\n' "$REV"
		printf 'family=%s\n' "$FAMILY"
		printf 'stack=%s\n' "$STACK"
		printf 'image=%s\n' "$IMAGE"
		printf 'ubuntu_version=%s\n' "$UBUNTU_VERSION"
		printf 'lab_name=%s\n' "$LAB_NAME"
		printf 'lab_prefix=%s\n' "$LAB_PREFIX"
		printf 'prepared_at=%s\n' "$(date --iso-8601=seconds)"
		"${GIT[@]}" status --short
	} >"$RUN_ROOT/build-metadata.txt"
}

build_image()
{
	local build_cpuset=${MIDR_BUILD_CPUSET:-0-15}

	if [ "${MIDR_SKIP_IMAGE_BUILD:-0}" = 1 ]; then
		docker image inspect "$IMAGE" >/dev/null 2>&1 ||
			die "MIDR_SKIP_IMAGE_BUILD=1 but image does not exist: $IMAGE"
		return
	fi

	DOCKER_BUILDKIT=0 docker build \
		--cpuset-cpus "$build_cpuset" \
		--force-rm \
		--network host \
		--tag "$IMAGE" \
		--build-arg UBUNTU_VERSION="$UBUNTU_VERSION" \
		--build-arg FRR_SOURCE_REV="$REV" \
		--file "$REPO_ROOT/docker/ubuntu-ci/Dockerfile" \
		"$REPO_ROOT" 2>&1 | tee "$RUN_ROOT/image-build.log"
	{
		docker run --rm "$IMAGE" /usr/lib/frr/bgpd --version
		docker run --rm "$IMAGE" /usr/lib/frr/midrd --version
		docker run --rm "$IMAGE" grep -q midrd /usr/lib/frr/frrcommon.sh &&
			echo 'frrcommon.sh starts midrd'
	} 2>&1 | tee "$RUN_ROOT/image-smoke.log"
}

deploy_lab()
{
	check_existing_lab
	containerlab deploy --topo "$TOPOLOGY" 2>&1 | tee "$RUN_ROOT/deploy.log"
	local running
	running=$(docker ps --format '{{.Names}}' | grep -cE "^${LAB_PREFIX}-" || true)
	[ "$running" -eq 15 ] || die "expected 15 running containers, found $running"
	containerlab inspect --topo "$TOPOLOGY" | tee "$RUN_ROOT/inspect.log"
}

run_acceptance()
{
	local acceptance_status tier1_status capture_status

	set +e
	MIDR_LAB_PREFIX="$LAB_PREFIX" \
		MIDR_LAB_FAMILY="$FAMILY" \
		MIDR_DEMO_WAIT_SECONDS="${MIDR_DEMO_WAIT_SECONDS:-600}" \
		MIDR_DEMO_POLL_SECONDS="${MIDR_DEMO_POLL_SECONDS:-10}" \
		"$ACCEPTANCE" 2>&1 | tee "$RUN_ROOT/acceptance.log"
	acceptance_status=${PIPESTATUS[0]}
	run_tier1_check
	tier1_status=$?
	ipv6_status=skipped
	if [ "$FAMILY" = ipv6 ]; then
		run_ipv6_check
		ipv6_status=$?
	fi
	run_capture post-convergence
	capture_status=$?
	set -e
	printf 'stack=%s family=%s acceptance=%s tier1-admission=%s ipv6-only=%s capture=%s\n' \
		"$STACK" "$FAMILY" "$acceptance_status" "$tier1_status" "$ipv6_status" \
		"$capture_status" | tee "$RUN_ROOT/result.txt"
	[ "$acceptance_status" -eq 0 ] && [ "$tier1_status" -eq 0 ] &&
		{ [ "$ipv6_status" = skipped ] || [ "$ipv6_status" -eq 0 ]; } &&
		[ "$capture_status" -eq 0 ]
}

run_ipv6_check()
{
	MIDR_LAB_PREFIX="$LAB_PREFIX" \
		MIDR_LAB_STACK="$STACK" \
		"$IPV6_CHECK" 2>&1 | tee "$RUN_ROOT/ipv6-only.log"
	return "${PIPESTATUS[0]}"
}

run_tier1_check()
{
	MIDR_LAB_PREFIX="$LAB_PREFIX" \
		MIDR_LAB_FAMILY="$FAMILY" \
		MIDR_LAB_STACK="$STACK" \
		MIDR_LAB_LOG_ROOT="$RUN_ROOT/logs-backbone" \
		"$TIER1_CHECK" 2>&1 | tee "$RUN_ROOT/tier1-admission.log"
	return "${PIPESTATUS[0]}"
}

# midrd keeps its state in show commands only; save them per node.
capture_midrd()
{
	local phase=$1 node dir cmd
	local cmds=('show midr self' 'show midr neighbors' 'show midr neighbors json'
		'show midr directory' 'show midr nodes' 'show midr links'
		'show midr join' 'show midr admission' 'show midr group2'
		'show midr group2-remote' 'show midr group2-snapshot'
		'show midr spf' 'show midr running-config')

	for node in b1 b2 b3 b4 b5 r1 r2 m1a m1b m2a z1 z2; do
		dir="$RUN_ROOT/evidence/$phase/$node"
		mkdir -p "$dir"
		for cmd in "${cmds[@]}"; do
			docker exec -u root "$LAB_PREFIX-$node" vtysh -d midrd -c "$cmd" \
				>"$dir/${cmd// /_}.txt" 2>&1 || return 1
		done
	done
	printf 'saved midrd state of 12 nodes under %s\n' "$RUN_ROOT/evidence/$phase"
}

run_capture()
{
	local phase=${1:-manual}

	if [ "$STACK" = midrd ]; then
		capture_midrd "$phase" 2>&1 | tee "$RUN_ROOT/capture-$phase.log"
		return "${PIPESTATUS[0]}"
	fi

	MIDR_LAB_PREFIX="$LAB_PREFIX" \
		MIDR_LAB_RUN_ROOT="$RUN_ROOT" \
		"$CAPTURE" "$phase" 2>&1 | tee "$RUN_ROOT/capture-$phase.log"
	return "${PIPESTATUS[0]}"
}

case "$MODE" in
	preflight)
		preflight
		;;
	build)
		preflight
		prepare_run_root
		build_image
		;;
	deploy)
		ensure_root
		preflight
		[ -f "$TOPOLOGY" ] || die "prepared topology is missing: $TOPOLOGY"
		deploy_lab
		;;
	all)
		ensure_root
		preflight
		check_existing_lab
		prepare_run_root
		build_image
		deploy_lab
		run_acceptance
		;;
	check)
		preflight
		[ -f "$TOPOLOGY" ] || die "prepared topology is missing: $TOPOLOGY"
		run_acceptance
		;;
	tier1-check)
		[ -f "$TOPOLOGY" ] || die "prepared topology is missing: $TOPOLOGY"
		run_tier1_check
		;;
	ipv6-check)
		[ "$FAMILY" = ipv6 ] || die "ipv6-check needs MIDR_LAB_FAMILY=ipv6"
		[ -f "$TOPOLOGY" ] || die "prepared topology is missing: $TOPOLOGY"
		run_ipv6_check
		;;
	capture)
		preflight
		run_capture manual
		;;
	destroy)
		ensure_root
		[ -f "$TOPOLOGY" ] || die "prepared topology is missing: $TOPOLOGY"
		containerlab destroy --topo "$TOPOLOGY" 2>&1 | tee "$RUN_ROOT/destroy.log"
		;;
	*)
		die "usage: [MIDR_LAB_STACK=midrd|bgpd] [MIDR_LAB_FAMILY=ipv4|ipv6] $0 [preflight|build|deploy|all|check|tier1-check|ipv6-check|capture|destroy]"
		;;
esac
