frr version 10.7.0-dev
frr defaults traditional
hostname t1
log file /etc/frr/logs/frr.log
!
! eth1 -> t2
interface eth1
 ip address 10.10.1.1/30
!
! eth2 -> t3
interface eth2
 ip address 10.10.3.1/30
!
! eth3 -> b1
interface eth3
 ip address 10.10.11.2/30
!
! eth4 -> b2
interface eth4
 ip address 10.10.12.2/30
!
! eth5 -> r1
interface eth5
 ip address 10.10.21.2/30
!
! eth6 -> m1a
interface eth6
 ip address 10.10.22.2/30
!
! eth7 -> z2
interface eth7
 ip address 10.10.32.2/30
!
interface lo
 ip address 10.99.0.201/32
!
router bgp 65201
 bgp router-id 10.0.0.201
 no bgp ebgp-requires-policy
 neighbor 10.10.1.2 remote-as 65202
 neighbor 10.10.3.2 remote-as 65203
 neighbor 10.10.11.1 remote-as 65101
 neighbor 10.10.12.1 remote-as 65102
 neighbor 10.10.21.1 remote-as 65111
 neighbor 10.10.22.1 remote-as 65112
 neighbor 10.10.32.1 remote-as 65192
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
!
