! Node g3a: Group 3 representative
! Transport 10.10.31.2 | ASN 65031 | Router-ID 10.0.31.1
frr version 10.0
hostname node-g3a
log file logs/bgpd-g3a.log debugging
log timestamp precision 3

debug bgp midr

router bgp 65031
  bgp router-id 10.0.31.1
  no bgp ebgp-requires-policy
  no bgp network import-check

  neighbor 10.10.11.2 remote-as 65011
  neighbor 10.10.11.2 ebgp-multihop 3
  neighbor 10.10.32.2 remote-as 65032
  neighbor 10.10.32.2 ebgp-multihop 3

  address-family link-state link-state
    distribute bgp-fabric-link-state
    neighbor 10.10.11.2 activate
    neighbor 10.10.32.2 activate
  exit-address-family

  midr transport-address 10.10.31.2
  midr group-id 3
  midr role group-rep
!
